inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'spec/acceptance/fixtures/**/*'
    - 'spec/unit/fixtures/**/*'
    - 'vendor/gems/**/*'
    - 'lib/contracts-ruby2/**/*'
    - 'lib/contracts-ruby3/**/*'

Style/HashSyntax:
  EnforcedShorthandSyntax: either
